name: Gradle wrapper validation

on:
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
  push:
    paths:
      - '**/gradle/wrapper/**'

jobs:
  validation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: gradle/wrapper-validation-action@v1.1.0